# Generated by Django 2.2.4 on 2020-10-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
