# Generated by Django 2.2.4 on 2020-10-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthorsApp', '0002_auto_20201013_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='BooksAuthorsApp.Author'),
        ),
    ]
